<!DOCTYPE html>
<html>
<head>
<title>{{.Path}}</title>
<meta name="go-import" content="{{.Path}} git {{.Repository}}">
<meta name="generator" content="https://github.com/melato/goget" />
</head>
<body>
<div>module:  {{.Path}}</div>
<div>repository: <a href="{{.Repository}}">{{.Repository}}</a></div>
<hr>
<div>
Generated by <a href="https://github.com/melato/goget">melato.org/goget</a>
</div>
</body>
</html>

